name: Build Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.11]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        python -m pip install -r requirements.txt
        python -m pip install pygame --pre
        python -m pip install pyinstaller
        
    - name: Debug Info
      run: |
        python --version
        pip list
        
    - name: Build with PyInstaller
      run: |
        python -m PyInstaller --onefile --windowed --debug=all "CS 89.py"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: game-${{ matrix.os }}
        path: dist/*
